config/routes.rb
Rails.application.routes.draw do
  get 'game', to: 'longest_word#game'

  get 'score', to: 'longest_word#score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/longest_word_controller.rb
require 'open-uri'
require 'json'

class LongestWordController < ApplicationController
  def game
    @grid = generate_grid(9)
    @start_time = Time.now
  end

  def score
    @grid = params[:grid].chars
    @start_time = Time.parse(params[:start_time])
    @attempt = params[:attempt]
    @result = run_game(@attempt, @grid, @start_time, Time.now)
  end

  def generate_grid(grid_size)
    Array.new(grid_size) { ("A".."Z").to_a[rand(26)] }
  end

  def run_game(attempt, grid, start_time, end_time)
    if word_in_grid?(attempt, grid) && word_exists?(attempt)
      get_score(attempt, grid, start_time, end_time)
    else
      time = end_time - start_time
      if !word_exists?(attempt)
        { status: "error", time: time, score: 0, message: "Your word is not an english word." }
      elsif !word_in_grid?(attempt, grid)
        { status: "error", time: time, score: 0, message: "Your word is not in the grid." }
      end
    end
  end

  def word_exists?(word)
    url = "https://wagon-dictionary.herokuapp.com/" + word
    response = open(url).read
    results = JSON.parse(response)
    results["found"]
  end

  def word_in_grid?(attempt, grid)
    tmp_array = attempt.upcase.chars
    @grid.each do |e|
      i = tmp_array.index(e)
      tmp_array.delete_at(i) if i
    end
    tmp_array.empty?
  end

  def get_score(attempt, grid, start_time, end_time)
    constant = 4
    time = end_time - start_time
    score = ((1 + attempt.length.fdiv(grid.length) * attempt.length) / time.to_f) * constant * 1000
    { status: "OK", time: time, score: score.to_i, message: "Well done!" }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/longest_word_helper.rb
module LongestWordHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-6 offset-sm-3 text-center"><%= yield %></div>
      </div>
    </div>
  </body>
</html>

app/views/longest_word/game.html.erb
<div class="row">
  <div class="col-2"></div>
  <% @grid.each do |letter| %>
    <div class="col-1"><%= letter %></div>
  <% end %>
</div>

<form action="<%= score_path %>">
    <input type="text" name="attempt">
    <input type="hidden" name="grid" value="<%= @grid.join %>">
    <input type="hidden" name="start_time" value="<%= @start_time %>">
    <input type="submit">
  </form>

app/views/longest_word/score.html.erb
<% if @result[:status] == "OK" %>
  <h1><%= @result[:message]%></h1>
  <h2>Elapsed time: <%= @result[:time]%> seconds</h2>
  <h2>Score: <%= @result[:score]%></h2>
<% else %>
  <h1><%= @result[:message] %></h1>
<% end %>

<%= link_to "Restart", game_path, class: "my-5 btn btn-primary" %>